- name: Configure Apache Spark
  hosts: tag_hadoop-master
  gather_facts: false
  become: true
  vars:
    spark_home: /opt/spark

  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: false

  tasks:
  - get_url:
      url: http://apache-mirror.rbc.ru/pub/apache/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz
      dest: /tmp/spark-2.2.0-bin-hadoop2.7.tgz
      force: no

  - unarchive: src=/tmp/spark-2.2.0-bin-hadoop2.7.tgz dest=/opt copy=no

  - file: dest={{ spark_home }} src=/opt/spark-2.2.0-bin-hadoop2.7 state=link force=yes
